import { useEffect, useMemo } from "react";
import { useLocation } from "react-router-dom";

export default function ReportsPrint() {
  const { search } = useLocation();
  const params = new URLSearchParams(search);
  const data = useMemo(() => {
    try { return JSON.parse(decodeURIComponent(params.get("data") || "{}")); } catch { return {}; }
  }, [search]);

  useEffect(() => {
    const t = setTimeout(() => window.print(), 300);
    return () => clearTimeout(t);
  }, []);

  return (
    <div className="mx-auto max-w-3xl p-6 print:p-0">
      <h1 className="text-2xl font-bold">{data.scheme || "Report"} Report</h1>
      <div className="text-sm text-muted-foreground">Period: {data.period}</div>
      <hr className="my-4" />
      <h2 className="text-lg font-semibold">Summary</h2>
      <ul className="mt-2 list-disc pl-6 text-sm">
        <li>Activity filter: {data.filteredType}</li>
        <li>Student participation: {data.studentParticipation}</li>
        <li>Certificates issued: {data.certificatesIssued}</li>
        <li>Attendance records: {data.attendanceRecords}</li>
      </ul>
      <h2 className="mt-6 text-lg font-semibold">Department-wise Activity</h2>
      <table className="mt-2 w-full text-sm">
        <thead>
          <tr className="text-left text-muted-foreground"><th className="p-2">Department</th><th className="p-2">Activities</th></tr>
        </thead>
        <tbody>
          {Object.entries(data.activityByDept || {}).map(([k, v]: any) => (
            <tr key={k} className="border-t"><td className="p-2">{k}</td><td className="p-2">{v}</td></tr>
          ))}
        </tbody>
      </table>
      <div className="mt-8 text-xs text-muted-foreground">Generated by GradFolia</div>
    </div>
  );
}
